-- ### Упражнение 6.6 

-- Задание 1 
SELECT * 
FROM employees; 


-- Задание 2 
SELECT GRADE  
FROM EXAM_RESULTS; 

 
-- Задание 3 
SELECT ELIGIBILITY_FOR_EXAM  
FROM STUDENT_ATTENDANCES  
WHERE STUDENT_ID = '77'; 

 
-- Задание 4 
SELECT *  
FROM FACULTY_LOGIN_DETAILS; 
 

-- Задание 5 
SELECT FIRST_NAME FROM FACULTIES NATURAL JOIN DEPARTMENTS; 
 

-- Задание 6 
SELECT ID||':'||' FIRST_NAME is '||FIRST_NAME FROM STUDENTS; 
 

-- Задание 7 
SELECT DISTINCT NAME FROM EXAMS; 

 

-- ### Упражнение 6.7 

-- Задание 1 
SELECT *  
FROM COURSES  
WHERE SEATED  
BETWEEN '2020-03-01' AND '2020-05-30'; 
 

-- Задание 2 
SELECT *  
FROM STUDENTS  
NATURAL LEFT JOIN EXAM_RESULTS USING(ID)  
WHERE GRADE > 95; 
 

-- Задание 3 
SELECT *   
FROM STUDENTS   
NATURAL LEFT JOIN EXAM_RESULTS USING(ID)   
WHERE GRADE >= 65 AND GRADE <= 70; 
 

-- Задание 4 
SELECT * 
FROM STUDENTS 
WHERE REGISTRATION_DATE > '2012-06-01'; 
 

-- Задание 5 
SELECT *  
FROM COURSES 
NATURAL JOIN DEPARTMENTS 
WHERE DEPARTMENT_ID = 10  
OR DEPARTMENT_ID = 30; 

 

-- Задание 6 
SELECT *  
FROM STUDENTS 
WHERE FIRST_NAME LIKE 'J%'; 
 

-- Задание 7 
SELECT *  
FROM STUDENTS  
NATURAL LEFT JOIN COURSES AS st USING(ID)  
WHERE st.ID = 190 OR st.ID = 193; 
 

 

-- Задание 8 
SELECT *  
FROM COURSES 
NATURAL JOIN DEPARTMENTS 
WHERE DEPARTMENT_ID = 30  
AND SESSION_ID = 200; 
 

-- Задание 9 
SELECT *  
FROM COURSES 
NATURAL JOIN DEPARTMENTS 
WHERE SESSION_ID = 200  
OR SESSION_ID = 300; 
 

-- Задание 10 
SELECT *  
FROM COURSES 
NATURAL JOIN DEPARTMENTS 
WHERE DEPARTMENT_ID = 20;