# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [1]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [3]:
torch.tensor([
    [-4, -3, -2, -6, -5, -2, -3, -4],
    [-1, -1, -1, -1, -1, -1, -1, -1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [4, 3, 2, 6, 5, 2, 3, 4],
])

tensor([[-4, -3, -2, -6, -5, -2, -3, -4],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1],
        [ 4,  3,  2,  6,  5,  2,  3,  4]])

In [6]:
# Исправил

t = torch.zeros(8, 8)
t[0] = torch.tensor([-4, -3, -2, -6, -5, -2, -3, -4])
t[1] = -1
t[-1] = t[0] * -1
t[-2] = t[1] * -1
t

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [60]:
k = torch.arange(2, 20+1, step=2) * torch.arange(3, 22, 2)
k

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [38]:
torch.arange(1, 110+1).reshape(11,10)[:,:-3]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [59]:
def foo(n, m):

    return torch.tensor([
        [0, 1],
        [2, 3]
    ]).repeat(n, m)[:n,:m]

foo(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [73]:
# r = torch.rand((4, 7)) * 20
r = torch.rand((4, 7)).uniform_(0, 20)
min_, max_ = r.min(), r.max()
(r - min_) / (max_ - min_)

tensor([[0.7089, 0.0338, 0.9060, 0.0821, 0.3954, 0.6083, 0.7798],
        [0.9422, 1.0000, 0.0493, 0.6321, 0.2517, 0.4306, 0.0741],
        [0.9999, 0.0822, 0.7899, 0.6878, 0.6730, 0.1900, 0.9989],
        [0.6143, 0.5635, 0.0000, 0.7259, 0.4080, 0.2361, 0.9710]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [80]:
ar1 = torch.randint(0, 11, size=(4, 7))
ar2 = torch.randint(0, 11, size=(4, 7))

ar1, ar2, torch.max(ar1, ar2)

(tensor([[ 8,  3,  4,  8,  7,  3,  3],
         [ 8,  1, 10,  4,  6,  5,  1],
         [ 3,  0,  4,  9,  6,  7,  1],
         [10,  8,  7,  4,  4,  8,  9]]),
 tensor([[ 1,  5,  3,  5,  2,  1,  6],
         [ 5,  7,  5,  6, 10,  8,  7],
         [ 7, 10,  5,  8,  6,  2,  2],
         [ 8,  5,  6,  5,  2,  6, 10]]),
 tensor([[ 8,  5,  4,  8,  7,  3,  6],
         [ 8,  7, 10,  6, 10,  8,  7],
         [ 7, 10,  5,  9,  6,  7,  2],
         [10,  8,  7,  5,  4,  8, 10]]))

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [96]:
tens = torch.randint(0, 100+1, size=(20,))
tens, tens.sort().indices[-2]

(tensor([ 6, 22,  8, 44, 10, 50, 66, 10, 17, 83,  0, 21, 87, 27,  4, 52, 98, 46,
         32, 45]),
 tensor(12))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [112]:
torch.arange(1, 8) + torch.arange(0, 101, step=10).reshape(-1, 1)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [116]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

a_2d - b_1d.reshape(-1, 1)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [148]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

(a == b).nonzero(as_tuple=True)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [133]:
torch.arange(9).view(3, 3).flip([1, 0])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python

a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [136]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [139]:
t = torch.arange(9).reshape(3, 3)
t[:, [0, 1]] = t[:, [1, 0]]
t

tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [144]:
t = torch.randint(0, 10+1, size=(8, 10))
idx = t.sum(1).argmin()
t, idx, t[idx]

(tensor([[ 1,  0,  8,  5,  7,  9,  3,  4,  5,  0],
         [ 4,  7,  6,  9,  1,  6,  1,  6,  3,  1],
         [ 0,  1,  1,  4,  6,  0,  4,  8,  3,  6],
         [ 7,  4,  2,  8, 10,  6,  2,  3,  8,  7],
         [ 8,  8,  6,  8,  2,  5,  6,  9,  2,  5],
         [ 4,  8,  8,  7,  1,  8,  2,  1,  7, 10],
         [ 9,  0,  4,  5,  5,  1,  6,  8, 10,  3],
         [ 2,  5,  9, 10,  1,  5,  6,  7,  9,  0]]),
 tensor(2),
 tensor([0, 1, 1, 4, 6, 0, 4, 8, 3, 6]))

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [146]:
t = torch.randint(0, 100+1, size=(20,))

t, t.clamp(min=30, max=70)

(tensor([ 91,  98,  22,  23,  41,   6,  61,  66,  18,   0,   6, 100,  37,  63,
          98,  93,  38,  23,  89,  65]),
 tensor([70, 70, 30, 30, 41, 30, 61, 66, 30, 30, 30, 70, 37, 63, 70, 70, 38, 30,
         70, 65]))

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [160]:
t1 = torch.randint(0, 10+1, size=(30, 3))
t2 = torch.randint(0, 10+1, size=(30, 3))
t1[t1 > t2], t1[t1 > t2].sum().item()

(tensor([ 8,  3,  9,  7,  7,  9,  9,  5,  8,  5,  8,  6, 10,  9,  9,  9,  9,  5,
          9,  7,  8,  7,  8,  8,  5,  7,  4,  6, 10,  4, 10,  7, 10,  8,  9, 10,
          5,  5,  4]),
 286)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [162]:
t = torch.randint(0, 10+1, size=(20, 20))
t, t[torch.arange(19), torch.arange(19)+1]

(tensor([[ 3,  1,  3,  2,  7,  3,  6,  0,  0,  3,  1,  5,  3,  9,  6, 10,  8,  4,
           6,  4],
         [ 9,  2,  5,  4,  0,  2,  8,  1,  8,  4,  4,  1,  7,  1, 10,  6,  5,  8,
           8,  6],
         [ 0,  7,  5,  5,  2,  6,  8,  7,  0,  7,  8,  2,  9,  1,  8,  4,  7,  9,
           3, 10],
         [ 8,  1,  8,  4,  3,  1,  7,  9,  1,  2,  4,  3,  2,  9, 10,  9,  7,  0,
          10,  4],
         [ 7, 10,  7,  0,  6,  2,  0, 10,  1,  3,  0, 10,  5,  2,  9,  9,  2,  1,
           4,  5],
         [ 7,  2,  2,  7,  8,  5,  4,  8,  7,  8,  6,  4,  4,  9,  0,  8,  6,  2,
           0,  4],
         [ 2,  6, 10,  2,  9,  3,  5,  8,  3,  7,  3,  8,  3,  9,  8,  5,  9,  5,
           9,  5],
         [ 1,  4,  6,  0,  3,  0,  2,  8,  9,  4,  4,  4,  8,  2,  2, 10,  4,  5,
           3,  3],
         [ 4,  1,  7,  9,  7,  3,  6,  1, 10,  4,  5,  7,  7,  6,  4,  3,  8,  2,
          10,  5],
         [ 2,  4,  6,  8,  7,  5,  5,  0,  6,  4,  9,  5,  8,  4,  2,  0,  0,  2,
         

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [167]:
ar1 = torch.randint(0, 11, size=(5, 10))
ar2 = torch.randint(0, 11, size=(5, 10))

ar1, ar2

(tensor([[ 0,  3,  6,  1,  3,  5,  2,  1,  8, 10],
         [ 6, 10,  8,  6,  7,  6,  0,  1,  7,  3],
         [ 4,  8,  9,  6, 10,  1,  1,  1,  3,  3],
         [ 3,  9, 10,  8,  4,  8,  8,  4,  0,  0],
         [ 6,  8,  7,  2,  8,  2,  6, 10,  9,  0]]),
 tensor([[ 8,  5,  9,  8,  5, 10,  8,  2,  1, 10],
         [ 1, 10,  2,  3,  0,  5,  8,  2,  7,  9],
         [ 9,  1,  7,  6,  0,  8, 10,  7,  4,  7],
         [ 2,  3,  8,  9,  7,  4,  8,  8,  4,  8],
         [10,  5,  2,  7,  1,  6,  2, 10,  5,  3]]))

In [168]:
ar1[ar1 == ar2] *= 2
ar1

tensor([[ 0,  3,  6,  1,  3,  5,  2,  1,  8, 20],
        [ 6, 20,  8,  6,  7,  6,  0,  1, 14,  3],
        [ 4,  8,  9, 12, 10,  1,  1,  1,  3,  3],
        [ 3,  9, 10,  8,  4,  8, 16,  4,  0,  0],
        [ 6,  8,  7,  2,  8,  2,  6, 20,  9,  0]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [169]:
ar1 = torch.randint(0, 11, size=(4, 7))
ar2 = torch.randint(0, 11, size=(4, 7))
ar3 = torch.randint(0, 11, size=(4, 7))

ar1, ar2, ar3

(tensor([[ 1,  4,  7,  9,  2,  9,  3],
         [ 1,  9, 10,  5,  5,  5,  5],
         [10, 10,  9,  0,  5,  7,  2],
         [10,  9,  5,  2,  3,  0,  7]]),
 tensor([[ 9,  6, 10,  8,  1,  0, 10],
         [ 9,  2, 10,  9,  6,  5,  6],
         [ 3,  8, 10,  1,  5,  8,  3],
         [ 3,  5,  0,  3,  7,  7, 10]]),
 tensor([[ 3,  5,  2,  6,  7,  2,  1],
         [ 0,  7, 10,  4,  1,  8,  9],
         [ 7,  5,  8,  9,  1,  8,  9],
         [ 3,  1,  6,  1,  7,  3,  5]]))

In [170]:
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0
ar1

tensor([[ 1,  4,  7,  9,  0,  9,  3],
        [ 1,  9, 10,  5,  5,  5,  5],
        [10, 10,  9,  0,  5,  7,  2],
        [10,  9,  0,  2,  3,  0,  7]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [171]:
ar1 = torch.randint(0, 20+1, size=(20, 5))
ar1

tensor([[ 7,  5,  7, 12,  3],
        [ 9,  4,  0, 19, 10],
        [ 5,  4,  8,  0,  5],
        [ 3, 10,  1,  1,  1],
        [13, 13, 11,  7, 19],
        [15, 11,  6,  4, 14],
        [17,  2, 18, 10, 18],
        [10,  9, 16,  5, 16],
        [18, 12, 13, 10,  2],
        [ 6,  9,  9, 16, 17],
        [14, 13,  1, 15,  3],
        [13, 17,  2,  1,  2],
        [20, 10, 20, 10,  9],
        [ 7, 16, 10, 20, 13],
        [19,  1, 11,  0, 10],
        [15, 12,  2, 12,  8],
        [10, 13,  3, 14, 18],
        [ 8,  3, 20,  2, 18],
        [ 2,  3,  2,  9, 13],
        [ 2, 19,  3, 10,  8]])

In [181]:
idx = ar1.argmax(1)
row, count = idx.unique(return_counts=True)
row[count >= 5]

tensor([0])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [190]:
ar1 = torch.rand(4, 7)

i = torch.div(ar1.argmax(), ar1.shape[1], rounding_mode='floor')
j = ar1.argmax() % ar1.shape[1]
ar1[i + 1:, j + 1:] = 0
ar1

tensor([[0.9456, 0.7112, 0.9362, 0.5075, 0.9956, 0.7069, 0.1897],
        [0.1675, 0.6166, 0.4691, 0.0442, 0.4131, 0.0000, 0.0000],
        [0.2803, 0.3146, 0.6881, 0.5659, 0.4874, 0.0000, 0.0000],
        [0.3361, 0.6867, 0.8172, 0.3351, 0.2198, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [191]:
from torch.nn import functional

t = torch.tensor([2, 3, 2, 2, 2, 1])
functional.one_hot(t - 1)

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [212]:
arr = torch.randint(0, 100+1, size=(20,))
mode_ = torch.mode(arr).values
mode_, (arr == mode_).nonzero(as_tuple=True)[0]

(tensor(9), tensor([ 1, 13]))

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [21]:
# Исправил
acc = 1000
t = torch.linspace(0, 10, acc)
range_ = (t * torch.sin(t) > 0.5).sum() / acc
range_.item()

0.5230000019073486

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [225]:
arr = torch.arange(2, 101)
for i in arr:
    arr = arr[(arr % i != 0) | (arr == i)]
arr

tensor([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
        67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [226]:
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
t2 = torch.tensor([2, 3, 4, 5, 6, 7, 8, 9, 10])

print(((t1 - t2) ** 2).sum().item())

9


1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [230]:
arr = torch.randint(0, 100+1, size=(20, 3))

In [235]:
arr[(arr ** 2).sum(axis=1).sort().indices]

tensor([[29, 13, 21],
        [35, 19, 46],
        [27, 65, 16],
        [36,  5, 67],
        [29, 55, 57],
        [32, 85,  0],
        [69, 55, 40],
        [80, 45, 39],
        [ 5, 95, 43],
        [ 9, 88, 60],
        [92, 45, 34],
        [29, 49, 92],
        [28, 60, 87],
        [74, 23, 83],
        [80, 42, 73],
        [80, 52, 73],
        [10, 95, 76],
        [82, 91,  9],
        [84, 40, 85],
        [93, 73, 87]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [252]:
t = torch.tensor([1, 3, 7, 10, 2, 6, 10, 1])
a = torch.diff(t)[:-1]
b = torch.diff(t.flip(0)).flip(0)[1:]
((a > 0) & (b > 0)).nonzero(as_tuple=True)[0] + 1

tensor([3, 6])

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [256]:
t = torch.rand((100,))
val = 0.5
idx = (t - val).abs().argmin()
t, idx, t[idx]

(tensor([0.0848, 0.5701, 0.0819, 0.5680, 0.9249, 0.3200, 0.6195, 0.9436, 0.3403,
         0.8403, 0.0230, 0.5524, 0.6858, 0.3128, 0.2413, 0.5770, 0.3968, 0.0704,
         0.1881, 0.2522, 0.5654, 0.7688, 0.9692, 0.6323, 0.2433, 0.0531, 0.1179,
         0.2234, 0.7442, 0.6063, 0.0870, 0.0048, 0.6104, 0.4663, 0.2192, 0.6356,
         0.6143, 0.4214, 0.8407, 0.8367, 0.2124, 0.3622, 0.0205, 0.1645, 0.6285,
         0.5899, 0.3745, 0.6396, 0.5233, 0.2247, 0.4161, 0.1731, 0.6348, 0.3828,
         0.9365, 0.1381, 0.7669, 0.9413, 0.4229, 0.7756, 0.8834, 0.5732, 0.8970,
         0.8483, 0.5537, 0.1500, 0.5644, 0.4294, 0.4004, 0.9406, 0.0468, 0.4795,
         0.6420, 0.1693, 0.8388, 0.4429, 0.2823, 0.5803, 0.1952, 0.3862, 0.1439,
         0.5115, 0.4881, 0.7916, 0.3462, 0.3539, 0.6611, 0.0541, 0.3652, 0.5532,
         0.4267, 0.8844, 0.0680, 0.3955, 0.9549, 0.4823, 0.9390, 0.5017, 0.8714,
         0.5105]),
 tensor(97),
 tensor(0.5017))

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [263]:
A = torch.tensor([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]], dtype=torch.float)
B = torch.tensor([[3, -1], [2, 1]], dtype=torch.float)
C = torch.tensor([[7, 21], [11, 8], [8, 4]], dtype=torch.float)

(torch.inverse(A) @ -C @ torch.inverse(B))

tensor([[ 1.0000e+00,  1.1921e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [266]:
a1 = torch.tensor([3, -3, 0, 7], dtype=torch.float)
a2 = torch.tensor([2, 2, 4, 7], dtype=torch.float)
a3 = torch.tensor([1, 2, 3, 4], dtype=torch.float)
a4 = torch.tensor([5, -4, 1, 3], dtype=torch.float)

arr = torch.vstack([a1, a2, a3, a4])

torch.linalg.matrix_rank(arr) == arr.shape[0]

tensor(False)

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

In [7]:
t = torch.normal(mean=0, std=10, size=(200,))
hist = torch.histogram(t, bins=20)
hist

torch.return_types.histogram(
hist=tensor([ 2.,  0.,  2.,  2.,  1.,  9., 13., 13., 15., 21., 23., 19., 20., 19.,
        15., 14.,  5.,  5.,  0.,  2.]),
bin_edges=tensor([-28.3530, -25.6889, -23.0248, -20.3607, -17.6966, -15.0325, -12.3684,
         -9.7043,  -7.0402,  -4.3761,  -1.7120,   0.9521,   3.6162,   6.2803,
          8.9444,  11.6085,  14.2726,  16.9367,  19.6008,  22.2649,  24.9290]))

In [ ]:
from matplotlib import plot as plt
        
plt.bar(t[:-1], hist).show()